cxx_library(
  name = 'mathutils',
  header_namespace = 'mathutils',
  exported_headers = subdir_glob([
    ('include', '**/*.hpp'),
  ]),
  srcs = glob([
    'src/**/*.cpp',
  ]),
  compiler_flags = [
    '-std=c++17',
  ],
  visibility = [
    '//...',
  ],
)